#include "OS/FreeBSDSysCallProvider.h"

using namespace soaap;

void FreeBSDSysCallProvider::initSysCalls() {
  // created from FreeBSD: head/sys/kern/syscalls.master 263318 2014-03-18 21:32:03Z attilio 
  addSysCall("syscall");
  addSysCall("exit");
  addSysCall("fork");
  addSysCall("read", true);
  addSysCall("write", true);
  addSysCall("open");
  addSysCall("close", true);
  addSysCall("wait4");
  addSysCall("compat.creat");
  addSysCall("link");
  addSysCall("unlink");
  addSysCall("obs_execv");
  addSysCall("chdir");
  addSysCall("fchdir", true);
  addSysCall("mknod");
  addSysCall("chmod");
  addSysCall("chown");
  addSysCall("break");
  addSysCall("compat4.getfsstat");
  addSysCall("compat.lseek", true);
  addSysCall("getpid");
  addSysCall("mount");
  addSysCall("unmount");
  addSysCall("setuid");
  addSysCall("getuid");
  addSysCall("geteuid");
  addSysCall("ptrace");
  addSysCall("recvmsg");
  addSysCall("sendmsg");
  addSysCall("recvfrom");
  addSysCall("accept");
  addSysCall("getpeername", true);
  addSysCall("getsockname", true);
  addSysCall("access");
  addSysCall("chflags");
  addSysCall("fchflags", true);
  addSysCall("sync");
  addSysCall("kill");
  addSysCall("compat.stat");
  addSysCall("getppid");
  addSysCall("compat.lstat");
  addSysCall("dup", true);
  addSysCall("pipe");
  addSysCall("getegid");
  addSysCall("profil");
  addSysCall("ktrace");
  addSysCall("compat.sigaction");
  addSysCall("getgid");
  addSysCall("compat.sigprocmask");
  addSysCall("getlogin");
  addSysCall("setlogin");
  addSysCall("acct");
  addSysCall("compat.sigpending");
  addSysCall("sigaltstack");
  addSysCall("ioctl", true);
  addSysCall("reboot");
  addSysCall("revoke");
  addSysCall("symlink");
  addSysCall("readlink");
  addSysCall("execve");
  addSysCall("umask");
  addSysCall("chroot");
  addSysCall("compat.fstat");
  addSysCall("compat.getkerninfo");
  addSysCall("compat.getpagesize");
  addSysCall("msync");
  addSysCall("vfork");
  addSysCall("obs_vread");
  addSysCall("obs_vwrite");
  addSysCall("sbrk");
  addSysCall("sstk");
  addSysCall("compat.mmap");
  addSysCall("vadvise");
  addSysCall("munmap");
  addSysCall("mprotect");
  addSysCall("madvise");
  addSysCall("obs_vhangup");
  addSysCall("obs_vlimit");
  addSysCall("mincore");
  addSysCall("getgroups");
  addSysCall("setgroups");
  addSysCall("getpgrp");
  addSysCall("setpgid");
  addSysCall("setitimer");
  addSysCall("compat.wait");
  addSysCall("swapon");
  addSysCall("getitimer");
  addSysCall("compat.gethostname");
  addSysCall("compat.sethostname");
  addSysCall("getdtablesize");
  addSysCall("dup2");
  addSysCall("#91");
  addSysCall("fcntl", true);
  addSysCall("select");
  addSysCall("#94");
  addSysCall("fsync", true);
  addSysCall("setpriority");
  addSysCall("socket");
  addSysCall("connect");
  addSysCall("compat.accept");
  addSysCall("getpriority");
  addSysCall("compat.send");
  addSysCall("compat.recv");
  addSysCall("compat.sigreturn");
  addSysCall("bind");
  addSysCall("setsockopt");
  addSysCall("listen");
  addSysCall("obs_vtimes");
  addSysCall("compat.sigvec");
  addSysCall("compat.sigblock");
  addSysCall("compat.sigsetmask");
  addSysCall("compat.sigsuspend");
  addSysCall("compat.sigstack");
  addSysCall("compat.recvmsg");
  addSysCall("compat.sendmsg");
  addSysCall("obs_vtrace");
  addSysCall("gettimeofday");
  addSysCall("getrusage");
  addSysCall("getsockopt");
  addSysCall("#119");
  addSysCall("readv", true);
  addSysCall("writev", true);
  addSysCall("settimeofday");
  addSysCall("fchown", true);
  addSysCall("fchmod", true);
  addSysCall("compat.recvfrom");
  addSysCall("setreuid");
  addSysCall("setregid");
  addSysCall("rename");
  addSysCall("compat.truncate");
  addSysCall("compat.ftruncate");
  addSysCall("flock", true);
  addSysCall("mkfifo");
  addSysCall("sendto");
  addSysCall("shutdown");
  addSysCall("socketpair");
  addSysCall("mkdir");
  addSysCall("rmdir");
  addSysCall("utimes");
  addSysCall("obs_4.2");
  addSysCall("adjtime");
  addSysCall("compat.getpeername");
  addSysCall("compat.gethostid");
  addSysCall("compat.sethostid");
  addSysCall("compat.getrlimit");
  addSysCall("compat.setrlimit");
  addSysCall("compat.killpg");
  addSysCall("setsid");
  addSysCall("quotactl");
  addSysCall("compat.quota");
  addSysCall("compat.getsockname");
  addSysCall("#151");
  addSysCall("#152");
  addSysCall("#153");
  addSysCall("nlm_syscall");
  addSysCall("nfssvc");
  addSysCall("compat.getdirentries");
  addSysCall("compat4.statfs");
  addSysCall("compat4.fstatfs", true);
  addSysCall("#159");
  addSysCall("lgetfh");
  addSysCall("getfh");
  addSysCall("compat4.getdomainname");
  addSysCall("compat4.setdomainname");
  addSysCall("compat4.uname");
  addSysCall("sysarch");
  addSysCall("rtprio");
  addSysCall("#167");
  addSysCall("#168");
  addSysCall("semsys");
  addSysCall("msgsys");
  addSysCall("shmsys");
  addSysCall("#172");
  addSysCall("freebsd6_pread", true);
  addSysCall("freebsd6_pwrite", true);
  addSysCall("setfib");
  addSysCall("ntp_adjtime");
  addSysCall("#177");
  addSysCall("#178");
  addSysCall("#179");
  addSysCall("#180");
  addSysCall("setgid");
  addSysCall("setegid");
  addSysCall("seteuid");
  addSysCall("#184");
  addSysCall("#185");
  addSysCall("#186");
  addSysCall("#187");
  addSysCall("stat");
  addSysCall("fstat", true);
  addSysCall("lstat");
  addSysCall("pathconf");
  addSysCall("fpathconf", true);
  addSysCall("#193");
  addSysCall("getrlimit");
  addSysCall("setrlimit");
  addSysCall("getdirentries", true);
  addSysCall("freebsd6_mmap");
  addSysCall("__syscall");
  addSysCall("freebsd6_lseek", true);
  addSysCall("freebsd6_truncate");
  addSysCall("freebsd6_ftruncate", true);
  addSysCall("__sysctl");
  addSysCall("mlock");
  addSysCall("munlock");
  addSysCall("undelete");
  addSysCall("futimes", true);
  addSysCall("getpgid");
  addSysCall("#208");
  addSysCall("poll");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("lkmnosys");
  addSysCall("compat7.__semctl");
  addSysCall("semget");
  addSysCall("semop");
  addSysCall("#223");
  addSysCall("compat7.msgctl");
  addSysCall("msgget");
  addSysCall("msgsnd");
  addSysCall("msgrcv");
  addSysCall("shmat");
  addSysCall("compat7.shmctl");
  addSysCall("shmdt");
  addSysCall("shmget");
  addSysCall("clock_gettime");
  addSysCall("clock_settime");
  addSysCall("clock_getres");
  addSysCall("ktimer_create");
  addSysCall("ktimer_delete");
  addSysCall("ktimer_settime");
  addSysCall("ktimer_gettime");
  addSysCall("ktimer_getoverrun");
  addSysCall("nanosleep");
  addSysCall("ffclock_getcounter");
  addSysCall("ffclock_setestimate");
  addSysCall("ffclock_getestimate");
  addSysCall("#244");
  addSysCall("#245");
  addSysCall("#246");
  addSysCall("clock_getcpuclockid2");
  addSysCall("ntp_gettime");
  addSysCall("#249");
  addSysCall("minherit");
  addSysCall("rfork");
  addSysCall("openbsd_poll");
  addSysCall("issetugid");
  addSysCall("lchown");
  addSysCall("aio_read");
  addSysCall("aio_write");
  addSysCall("lio_listio");
  addSysCall("#258");
  addSysCall("#259");
  addSysCall("#260");
  addSysCall("#261");
  addSysCall("#262");
  addSysCall("#263");
  addSysCall("#264");
  addSysCall("#265");
  addSysCall("#266");
  addSysCall("#267");
  addSysCall("#268");
  addSysCall("#269");
  addSysCall("#270");
  addSysCall("#271");
  addSysCall("getdents", true);
  addSysCall("#273");
  addSysCall("lchmod");
  addSysCall("netbsd_lchown");
  addSysCall("lutimes");
  addSysCall("netbsd_msync");
  addSysCall("nstat");
  addSysCall("nfstat", true);
  addSysCall("nlstat");
  addSysCall("#281");
  addSysCall("#282");
  addSysCall("#283");
  addSysCall("#284");
  addSysCall("#285");
  addSysCall("#286");
  addSysCall("#287");
  addSysCall("#288");
  addSysCall("preadv", true);
  addSysCall("pwritev", true);
  addSysCall("#291");
  addSysCall("#292");
  addSysCall("#293");
  addSysCall("#294");
  addSysCall("#295");
  addSysCall("#296");
  addSysCall("compat4.fhstatfs");
  addSysCall("fhopen");
  addSysCall("fhstat");
  addSysCall("modnext");
  addSysCall("modstat");
  addSysCall("modfnext");
  addSysCall("modfind");
  addSysCall("kldload");
  addSysCall("kldunload");
  addSysCall("kldfind");
  addSysCall("kldnext");
  addSysCall("kldstat");
  addSysCall("kldfirstmod");
  addSysCall("getsid");
  addSysCall("setresuid");
  addSysCall("setresgid");
  addSysCall("obs_signanosleep");
  addSysCall("aio_return");
  addSysCall("aio_suspend");
  addSysCall("aio_cancel", true);
  addSysCall("aio_error");
  addSysCall("oaio_read");
  addSysCall("oaio_write");
  addSysCall("olio_listio");
  addSysCall("yield");
  addSysCall("obs_thr_sleep");
  addSysCall("obs_thr_wakeup");
  addSysCall("mlockall");
  addSysCall("munlockall");
  addSysCall("__getcwd");
  addSysCall("sched_setparam");
  addSysCall("sched_getparam");
  addSysCall("sched_setscheduler");
  addSysCall("sched_getscheduler");
  addSysCall("sched_yield");
  addSysCall("sched_get_priority_max");
  addSysCall("sched_get_priority_min");
  addSysCall("sched_rr_get_interval");
  addSysCall("utrace");
  addSysCall("compat4.sendfile", true);
  addSysCall("kldsym");
  addSysCall("jail");
  addSysCall("nnpfs_syscall");
  addSysCall("sigprocmask");
  addSysCall("sigsuspend");
  addSysCall("compat4.sigaction");
  addSysCall("sigpending");
  addSysCall("compat4.sigreturn");
  addSysCall("sigtimedwait");
  addSysCall("sigwaitinfo");
  addSysCall("__acl_get_file");
  addSysCall("__acl_set_file");
  addSysCall("__acl_get_fd");
  addSysCall("__acl_set_fd");
  addSysCall("__acl_delete_file");
  addSysCall("__acl_delete_fd");
  addSysCall("__acl_aclcheck_file");
  addSysCall("__acl_aclcheck_fd");
  addSysCall("extattrctl");
  addSysCall("extattr_set_file");
  addSysCall("extattr_get_file");
  addSysCall("extattr_delete_file");
  addSysCall("aio_waitcomplete");
  addSysCall("getresuid");
  addSysCall("getresgid");
  addSysCall("kqueue");
  addSysCall("kevent", true);
  addSysCall("#364");
  addSysCall("#365");
  addSysCall("#366");
  addSysCall("#367");
  addSysCall("#368");
  addSysCall("#369");
  addSysCall("#370");
  addSysCall("extattr_set_fd", true);
  addSysCall("extattr_get_fd", true);
  addSysCall("extattr_delete_fd", true);
  addSysCall("__setugid");
  addSysCall("#375");
  addSysCall("eaccess");
  addSysCall("afs3_syscall");
  addSysCall("nmount");
  addSysCall("#379");
  addSysCall("#380");
  addSysCall("#381");
  addSysCall("#382");
  addSysCall("#383");
  addSysCall("__mac_get_proc");
  addSysCall("__mac_set_proc");
  addSysCall("__mac_get_fd", true);
  addSysCall("__mac_get_file");
  addSysCall("__mac_set_fd", true);
  addSysCall("__mac_set_file");
  addSysCall("kenv");
  addSysCall("lchflags");
  addSysCall("uuidgen");
  addSysCall("sendfile", true);
  addSysCall("mac_syscall");
  addSysCall("getfsstat");
  addSysCall("statfs");
  addSysCall("fstatfs", true);
  addSysCall("fhstatfs");
  addSysCall("#399");
  addSysCall("ksem_close");
  addSysCall("ksem_post");
  addSysCall("ksem_wait");
  addSysCall("ksem_trywait");
  addSysCall("ksem_init");
  addSysCall("ksem_open");
  addSysCall("ksem_unlink");
  addSysCall("ksem_getvalue");
  addSysCall("ksem_destroy");
  addSysCall("__mac_get_pid");
  addSysCall("__mac_get_link");
  addSysCall("__mac_set_link");
  addSysCall("extattr_set_link");
  addSysCall("extattr_get_link");
  addSysCall("extattr_delete_link");
  addSysCall("__mac_execve");
  addSysCall("sigaction");
  addSysCall("sigreturn");
  addSysCall("#418");
  addSysCall("#419");
  addSysCall("#420");
  addSysCall("getcontext");
  addSysCall("setcontext");
  addSysCall("swapcontext");
  addSysCall("swapoff");
  addSysCall("__acl_get_link");
  addSysCall("__acl_set_link");
  addSysCall("__acl_delete_link");
  addSysCall("__acl_aclcheck_link");
  addSysCall("sigwait");
  addSysCall("thr_create");
  addSysCall("thr_exit");
  addSysCall("thr_self");
  addSysCall("thr_kill");
  addSysCall("#434");
  addSysCall("#435");
  addSysCall("jail_attach");
  addSysCall("extattr_list_fd", true);
  addSysCall("extattr_list_file");
  addSysCall("extattr_list_link");
  addSysCall("#440");
  addSysCall("ksem_timedwait");
  addSysCall("thr_suspend");
  addSysCall("thr_wake");
  addSysCall("kldunloadf");
  addSysCall("audit");
  addSysCall("auditon");
  addSysCall("getauid");
  addSysCall("setauid");
  addSysCall("getaudit");
  addSysCall("setaudit");
  addSysCall("getaudit_addr");
  addSysCall("setaudit_addr");
  addSysCall("auditctl");
  addSysCall("_umtx_op");
  addSysCall("thr_new");
  addSysCall("sigqueue");
  addSysCall("kmq_open");
  addSysCall("kmq_setattr");
  addSysCall("kmq_timedreceive");
  addSysCall("kmq_timedsend");
  addSysCall("kmq_notify");
  addSysCall("kmq_unlink");
  addSysCall("abort2");
  addSysCall("thr_set_name");
  addSysCall("aio_fsync");
  addSysCall("rtprio_thread");
  addSysCall("#467");
  addSysCall("#468");
  addSysCall("#469");
  addSysCall("#470");
  addSysCall("sctp_peeloff");
  addSysCall("sctp_generic_sendmsg");
  addSysCall("sctp_generic_sendmsg_iov");
  addSysCall("sctp_generic_recvmsg");
  addSysCall("pread", true);
  addSysCall("pwrite", true);
  addSysCall("mmap");
  addSysCall("lseek", true);
  addSysCall("truncate");
  addSysCall("ftruncate", true);
  addSysCall("thr_kill2");
  addSysCall("shm_open");
  addSysCall("shm_unlink");
  addSysCall("cpuset");
  addSysCall("cpuset_setid");
  addSysCall("cpuset_getid");
  addSysCall("cpuset_getaffinity");
  addSysCall("cpuset_setaffinity");
  addSysCall("faccessat", true);
  addSysCall("fchmodat", true);
  addSysCall("fchownat", true);
  addSysCall("fexecve", true);
  addSysCall("fstatat", true);
  addSysCall("futimesat", true);
  addSysCall("linkat");
  addSysCall("mkdirat", true);
  addSysCall("mkfifoat", true);
  addSysCall("mknodat", true);
  addSysCall("openat", true);
  addSysCall("readlinkat", true);
  addSysCall("renameat");
  addSysCall("symlinkat", true, 1);
  addSysCall("unlinkat", true);
  addSysCall("posix_openpt");
  addSysCall("gssd_syscall");
  addSysCall("jail_get");
  addSysCall("jail_set");
  addSysCall("jail_remove");
  addSysCall("closefrom");
  addSysCall("__semctl");
  addSysCall("msgctl");
  addSysCall("shmctl");
  addSysCall("lpathconf");
  addSysCall("obs_cap_new");
  addSysCall("__cap_rights_get", true, 1);
  addSysCall("cap_enter");
  addSysCall("cap_getmode");
  addSysCall("pdfork");
  addSysCall("pdkill", true);
  addSysCall("pdgetpid", true);
  addSysCall("#521");
  addSysCall("pselect");
  addSysCall("getloginclass");
  addSysCall("setloginclass");
  addSysCall("rctl_get_racct");
  addSysCall("rctl_get_rules");
  addSysCall("rctl_get_limits");
  addSysCall("rctl_add_rule");
  addSysCall("rctl_remove_rule");
  addSysCall("posix_fallocate", true);
  addSysCall("posix_fadvise", true);
  addSysCall("wait6");
  addSysCall("cap_rights_limit", true);
  addSysCall("cap_ioctls_limit", true);
  addSysCall("cap_ioctls_get", true);
  addSysCall("cap_fcntls_limit", true);
  addSysCall("cap_fcntls_get", true);
  addSysCall("bindat", true);
  addSysCall("connectat", true);
  addSysCall("chflagsat", true);
  addSysCall("accept4");
  addSysCall("pipe2");
  addSysCall("aio_mlock");
  addSysCall("procctl");
}
